<#--
   Copyright 2014-2016 PetaByte Research Ltd.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 -->

<#include "/includes/header.ftl">

<#-- ###########################################################################

Model:

	allCount
		Pass the count of elements in the whole query.

	count
		Pass the count of elements showed on the page, it is needed to generate
		pager URLs.
	
	counts
		Pass the options for elements per page setting as an array.
		
	filter
		Optional, the value of 'filter' GET parameter, used to generate pager
		URLs.
		
	filteredCount
		Pass the count of elements matching the filters in the whole query.

	objs
		Pass your objects as List<Map<String,Object>>. It can be generated by
		JdbcTemplate or using commons-beanutils BeanMap.
		
	page
		Pass the current page number (starting with 1), it is needed to generate
		pager URLs.
	
	pages
		Pass the number of pages, it is needed to generate pager URLs.

############################################################################ -->

<#if !allCount?? || !count?? || !counts?? || !filteredCount?? || !objs?? || !page?? || !pages??>
	<p class="text-danger">
		Some of these model attributes are missing: allCount, count, counts, filteredCount, objs, page, pages.
	</p>
<#else>

<#if filter??>
	<#assign removeFilter>/organizations/${count}/1</#assign>
<#else>
	<#assign removeFilter = "#" />
</#if>

<#-- NAVBAR ---------------------------------------------------------------- -->

<div class="row">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#details-navbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="details-navbar">
				<ul class="nav navbar-nav">
					<li><a href="#">
						<#if filteredCount != allCount>${filteredCount} / </#if>
						${allCount} <@label "organizations.count" />
					</a></li>					
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#"></a></li>
					<form class="navbar-form navbar-left" role="search">
						<div class="input-group">
							<span class="input-group-addon" data-toggle="tooltip" data-placement="top" title="<@label "organizations.filter.hint" "organizations.filter.hint" />"><span class="glyphicon glyphicon-filter"></span></span>
							<input id="filter" name="filter" <#if filter??>value="${filter}"</#if> type="text" class="form-control" placeholder="<@label 'list.filter', '' />" />
							<span class="input-group-btn">
								<a class="btn btn-default" href="${removeFilter}"><span class="glyphicon glyphicon-remove"></span></a>									
							</span>
						</div>
						<button type="submit" style="display:none">Submit</button>
					</form>
				</ul>
			</div>
		</div>
	</nav>
</div>

<#-- TABLE ----------------------------------------------------------------- -->

<#if 0 == objs?size>
	<p class="text-center text-primary notfound"><strong><@spring.messageText 'organizations.empty', '' /></strong></p>
</#if>

<div class="row"><table class="table table-striped col-md-12 list-table">
	<#list objs as obj>
		<tr>
			<td class="col-md-10">
				<strong><a href="/organization/${obj.id}"><#if obj.name??>${obj.name}<#else>(null)</#if></a></strong>
				<br/>
				<#if obj.type??>${obj.type}</#if>&nbsp;
			</td>			
			<td class="col-md-2">
				<#if obj.calls?? && obj.calls &gt; 0>
					<strong>${obj.calls}</strong>&nbsp;<@label "organizations.calls" />
					<br/>
				</#if>
				<#if obj.wins?? && obj.wins &gt; 0>
					<strong>${obj.wins}</strong>&nbsp;<@label "organizations.wins" />
				</#if>
			</td>
		</tr>
	</#list>
</table></div>

<#-- PAGER ----------------------------------------------------------------- -->

<#assign urlFormat>/organizations/$C/$P<#if filter?? && filter?length &gt; 0>?filter=${filter}</#if></#assign>
<@pager pages page counts count urlFormat "$P" "$C" />

<!-- Query time: ${queryTime} ms -->

</#if>

<#include "/includes/footer.ftl">